# Generated by Django 3.0.6 on 2020-06-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonneteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
